### PR TITLE
fix #78: Add additional metadata for function expressions

### LINKED ISSUE #78: Enhance function expression metadata
```js
export let subtract = function(a, b){
  return a - b;
}

export let multiply = (a, b = 1) => {
	return a * b;
}
```

These `VariableDeclaration` items contain `FunctionExpression` and `ArrowFunctionExpression` within them.

We should treat these similar to `FunctionDeclaration` and make parameters and return values available in the output.

### PR DESCRIPTION
**Pull request by ekhaled**
closes #78

### CODE REVIEW

**Comment by alexprey** [comment]
Hi, thanks for changes! Looks very nice.
However, I not sure about data structure changes in `SvelteDataItem`, I'm think that it is not a good idea to make that type messy. I need a time to think about that and comeback later

**Comment by ekhaled** [comment]
If you have any suggestions, let me know. Happy to implement it 😄

**Comment by alexprey** [comment]
Ok, I'm thinking on that and that what I think:
Params and return metadata are used in functions, and actually functions can be used anywhere in the JS code: component can have methods, variables can be a function, parameter can be a function, return type also can be a function. And if you look at [JSDocType](https://github.com/alexprey/sveltedoc-parser/blob/a927813bb5c72a52963c1d40a1a753e7ff907159/typings.d.ts#L66) you can see that I already provide additional information about type. So, let to create a new type for `JSDocType`:

```
export interface JSDocTypeFunction extends JSDocTypeBase {
    kind: 'function';
    params?: SvelteMethodParamItem[];
    return?: SvelteMethodReturnItem;
}
```

I think that is a better way to do that. If you have any ideas or points, please mention that, I'm open for discussion

**Comment by ekhaled** [comment]
That sounds absolutely fine to me.
Are you able to make the relevant commits and update this PR?

**Comment by alexprey** [comment]
Ok, I'm update your PR and merge it. Try to do it on this week and plan release for the next week.
Thanks for you contribution!

**Comment by alexprey** [comment]
@ekhaled thanks for your contribution to that library! Sorry, that I was too much slow to make last fixes and publish the new version of library 🐱

**Pull request merged**
