### PR TITLE
infer type from default value

### PR DESCRIPTION
**Pull request by hontas**
This would be nice to have in some form so we don't have to declare @type when it's easy to infer from value.

How do you feel about it?
It's not a pretty solution I know, but I wanted to start the discussion early ;)

### CODE REVIEW

**Comment by alexprey** [comment]
Hi! Really interesting changes! Thanks for contributing!

However, we already have same logic for v2 parser and it placed in `jsdoc.js` file, please check `parseJSTypeFromValueNode` method. It would be nice to use this method here, maybe some modifications are required for that. Can you please update your MR?

------

Additionaly I'm just found issue with default type value of the node:
```
type: jsdoc.DEFAULT_TYPE,
```
It is my mistake and it's totally wrong, because it is not complined with `JSDocType` interface that described in `typings.d.ts` file. So, it should be changed on something like:
```
type: { kind: 'type', text: 'any', type: 'any' }
```

Can you please also include this changes into MR?
Thanks for contributing!

**Comment by hontas** [comment]
Sure thing, I'll have a look at it later 👍

**Comment by hontas** [comment]
Updated to use `{ kind: 'type', text: 'any', type: 'any' }` instead of `'any'` and moved the infer-type-logic to utils. But looking at `parseJSTypeFromValueNode ` it seems the data structure is so different I didn't try to merge them, hope you think that's ok.

Also a lot of tests are failing in regards to location, but since they were failing before I didn't attempt to fix them now.

**Comment by alexprey** [comment]
Ok, thats fine. Just run tests on your changes and all are success!

**Comment by hontas** [comment]
Didn't wanna bother with an issue so I'll ask here: how to document top level description and examples? Not sure what the jsdoc standard way is or if a special @keyword should be used for this. Is it possible now?

**Comment by alexprey** [comment]
Actually it is a big question how to identify global component documentation, for v2 components it was clear for understanding how component should be documented.
For v3 components it has many ways. But I prefer to use something like this:
```
<script>
/**
 * The component description
 * @component ComponentName
 */
/**
 * The component identifier.
 * @type {int}
 */
let identifier = 1;
</script>
```
or 
```
<!--
/**
 * The component description
 * @component ComponentName
 */
-->
<h1>Header</h1>
```

**Comment by hontas** [comment]
Coolio :) PR ready for you: #20

**Pull request merged**
